paths:
  /login:
    post:
      tags:
        - Onboarding
      summary: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          description: The email of the user
          example: "sample@mail.com"
          default: "sample@mail.com"
        pass:
          type: string
          description: The password of the user
          example: "password@123"
          default: "password@123"
      required:
        - email
        - pass

    LoginResponse:
      type: object
      properties:
        message:
          type: string
          description: A message to indicate the login status
          example: "logged in"
        token:
          type: string
          description: The token for the user
          example: "token"
        user:
          type: object
          properties:
            id:
              type: string
              description: Unique identifier for the user
              example: "123e4567-e89b-12d3-a456-426614174000"
            full_name:
              type: string
              description: Full Name
              example: John Doe
            email:
              type: string
              description: Email
              example: "sample@mail.com"
            phone:
              type: string
              description: Phone
              example: "1234567890"
            role:
              type: string
              description: Role
              example: "Software Engineer"
            department:
              type: string
              description: Department
              example: "raipur"
            createdAt:
              type: string
              format: date-time
              description: Date of creation
              example: "2021-08-10T09:00:00Z"
          required:
            - id
            - email
            - role
            - createdAt
